### ISSUE TITLE
Handling Ctrl-C

### ISSUE THREAD

**Issue by AdrieanKhisbe** [dahlia/logging-spinner#3]
I tried to use it on a script fetching data in database, and decided to give up the call since taking so long.
However I cannot terminate the program anymore. :/

```
Traceback (most recent call last):
  File "generate_indicators_datasets.py", line 52, in <module>
file_name = sys.argv[1] if len(sys.argv) > 1 else "generated-dataset.csv"
  File "generate_indicators_datasets.py", line 20, in generate_datasets
    indicators = []
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2645, in all
    return list(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 75, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 437, in _instance
    loaded_instance, populate_existing, populators)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 497, in _populate_full
    for key, getter in populators["quick"]:
KeyboardInterrupt
⠋ Fetching User in the database
```

**Comment by AdrieanKhisbe** [comment]
(up?)
